/*
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

/***********************************************************************************************************************
 * Includes
 ***********************************************************************************************************************/
#include "rm_gptp_sys_baremetal.h"

/***********************************************************************************************************************
 * Exported global function
 ***********************************************************************************************************************/
extern gptp_sys_baremetal_instance_ctrl_t * rm_gptp_sys_baremetal_set_instance_ctrl(void);

/***********************************************************************************************************************
 * Functions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Setup timer and queue.
 **********************************************************************************************************************/
fsp_err_t rm_gptp_sys_baremetal_setup (gptp_sys_port_ctrl_t * p_ctrl, gptp_sys_port_cfg_t * p_cfg)
{
    fsp_err_t err = FSP_SUCCESS;
    gptp_sys_baremetal_instance_ctrl_t * p_instance_ctrl = (gptp_sys_baremetal_instance_ctrl_t *) p_ctrl;

    p_instance_ctrl->p_cfg     = p_cfg;
    p_instance_ctrl->p_context = NULL;

    /* Initialize time. */
    err = rm_gptp_sys_baremetal_timer_setup(p_ctrl, p_cfg);

    /* Initialize queue. */
    if (FSP_SUCCESS == err)
    {
        err = rm_gptp_sys_baremetal_queue_setup(p_ctrl, p_cfg);
    }

    return err;
}

/***********************************************************************************************************************
 * Return an instance control of this porting layer.
 **********************************************************************************************************************/
BSP_WEAK_REFERENCE gptp_sys_baremetal_instance_ctrl_t * rm_gptp_sys_baremetal_set_instance_ctrl (void)
{
    /* Not implemented in this code and must be generated by configuration. */
    BSP_CFG_HANDLE_UNRECOVERABLE_ERROR(0);

    return NULL;
}
